server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
#    url: jdbc:h2:file:~/data/employee_db
    username: chandan
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
#    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
#    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://localhost:9296

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}